web/urls.py
from django.urls import path

from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index,name='index'),
    path('productosPorCategoria/<int:categoria_id>',views.productosPorCategoria,name='productosPorCategoria'),
    path('productosPorNombre',views.productosPorNombre,name='productosPorNombre'),
    path('producto/<int:producto_id>',views.productoDetalle,name='producto'),
    path('carrito',views.carrito,name='carrito'),
    path('agregarCarrito/<int:producto_id>',views.agregarCarrito,name='agregarCarrito'),
    path('eliminarProductoCarrito/<int:producto_id>',views.eliminarProductoCarrito,name='eliminarProductoCarrito'),
    path('limpiarCarrito',views.limpiarCarrito,name='limpiarCarrito'),
    path('crearUsuario',views.crearUsuario,name='crearUsuario'),
    path('cuenta',views.cuentaUsuario,name='cuentaUsuario'),
    path('actualizarCliente',views.actualizarCliente,name='actualizarCliente'),
    path('login',views.loginUsuario,name='loginUsuario'),
    path('logout',views.logoutUsuario,name='logoutUsuario'),
    path('registrarPedido',views.registrarPedido,name='registrarPedido'),
    path('confirmarPedido',views.confirmarPedido,name='confirmarPedido'),
    path('gracias',views.gracias,name='gracias')
] 

web/templates/includes/footer.html
{% load static %}
<!--footer-->
    <div class="container-fluid blog-sb-widgets page-styling site-footer">
        <div class="row">
            <div class="col-sm-12 col-md-4 widget align-center-tablet f-logo-wrap">
                <a href="index.html" class="f-logo">
                    <img src="{% static 'img/logo.png' %}" alt="">
                </a>
                <p>Proyecto Ecommerce con Django para EdTeam</p>
                <button class="btn callback">Contacto</button>
            </div>
        </div>
    </div>

web/templates/includes/header.html
{% load static %}
    <!--header-->
    <div class="site-header">

        <p class="h-logo">
            <a href="/"><img src="{% static 'img/logo.png' %}" alt="EdShop"></a>
        </p><!--
    No Space
    --><div class="h-shop">

        <form method="post" action="{% url 'web:productosPorNombre' %}" class="h-search" id="h-search">
            {% csrf_token %}
            <input type="text" name="nombre" placeholder="Buscar...">
            <button type="submit"><i class="ion-search"></i></button>
        </form>

        <ul class="h-shop-links">
            <li class="h-search-btn" id="h-search-btn"><i class="ion-search"></i></li>
            
            <li class="h-shop-icon h-profile">
                <a href="auth.html" title="My Account">
                    <i class="ion-android-person"></i>
                </a>
                <ul class="h-profile-links">
                    <li><a href="/login">Login / Registro</a></li>
                    <li><a href="/logout">Logout</a></li>
                </ul>
            </li>

            {% include 'includes/header_carrito.html' %}


        </ul>
    </div></div>

web/templates/includes/header_carrito.html
<li class="h-cart">
    <a class="cart-contents" href="cart.html">
        <p class="h-cart-icon">
            <i class="ion-android-cart"></i>
            <span>{{request.session.cart.items|length}}</span>
        </p>
        <p class="h-cart-total">${{request.session.cartMontoTotal}}</p>
    </a>
    <div class="widget_shopping_cart">
        <div class="widget_shopping_cart_content">
            <ul class="cart_list">
                {% for key,value in request.session.cart.items %}
                <li>
                    <a href="{% url 'web:eliminarProductoCarrito' value.producto_id %}" class="remove">&times;</a>
                    <a href="#">
                        <img src="{{value.imagen}}" alt="">
                        {{value.nombre}}
                    </a>
                    <span class="quantity">{{value.cantidad}} &times; ${{value.subtotal}}</span>
                </li>
                {% endfor %}
            </ul>
            <p class="total"><b>Total:</b> ${{request.session.cartMontoTotal}}</p>
            <p class="buttons">
                <a href="{% url 'web:carrito' %}" class="button">Ver Carrito</a>
                <a href="#" class="button">Pedido</a>
            </p>
        </div>
    </div>
</li>

web/templates/includes/navbar.html
<!--navbar-->
<div class="container-fluid page-styling site-header-before">
    <div class="row">
        <div class="col-lg-4">
            <ul class="links_list links_list-align-left align-center-desktop topbar-social">
                <li>
                    <p class="links_list-value">
                        <a href="http://facebook.com" target="_blank" rel="nofollow">
                            <i class="fa fa-facebook"></i>
                        </a>
                    </p>
                </li>
            </ul>
        </div>
        <div class="col-lg-8">
            <ul class="links_list links_list-align-right align-center-desktop topbar-contacts">
                <li>
                    <p class="links_list-label">
                        Dirección
                    </p>
                    <p class="links_list-value">
                        <a href="http://maps.google.com" target="_blank" rel="nofollow">Calle 123,Lima Perú</a>
                    </p>
                </li>
                <li>
                    <p class="links_list-label">
                        Contacto
                    </p>
                    <p class="links_list-value">
                        <a href="mailto:support@email.com">Support@Email.com</a>
                    </p>
                </li>
                <li>
                    <p class="links_list-label">
                        Telefono
                    </p>
                    <p class="links_list-value">
                        <a href="tel:4785929899">(478)-592-9899</a>
                    </p>
                </li>
            </ul>
        </div>
    </div>
</div>

web/templates/includes/relacionados.html
<h2 class="prod-related-ttl">Related Products</h2>
    <div class="row prod-items prod-items-4">
        <article class="cf-sm-6 cf-md-6 cf-lg-3 col-xs-6 col-sm-6 col-md-6 col-lg-3 sectgl-item sectgl-item">
            <div class="sectgl prod-i">
                <div class="prod-i-top">
                    <a class="prod-i-img" href="product.html">
                        <img src="http://placehold.it/290x258" alt="">
                    </a>
                    <div class="prod-i-actions">
                        <div class="prod-i-actions-in">
                            <div class="prod-li-favorites">
                                <a href="wishlist.html" class="hover-label add_to_wishlist"><i class="icon ion-heart"></i><span>Add to Wishlist</span></a>
                            </div>
                            <p class="prod-quickview">
                                <a href="#" class="hover-label quick-view"><i class="icon ion-plus"></i><span>Quick View</span></a>
                            </p>
                            <p class="prod-i-cart">
                                <a href="#" class="hover-label prod-addbtn"><i class="icon ion-android-cart"></i><span>Add to Cart</span></a>
                            </p>
                            <p class="prod-li-compare">
                                <a href="compare.html" class="hover-label prod-li-compare-btn"><span>Compare</span><i class="icon ion-arrow-swap"></i></a>
                            </p>
                        </div>
                    </div>
                    <p class="prod-i-badge"><span>Sale</span></p>
                </div>
                <div class="prod-i-bot">
                    <div class="prod-i-info">
                        <p class="prod-i-price">$70.00</p>
                        <p class="prod-i-categ"><a href="catalog-gallery.html">Electricity</a></p>
                    </div>
                    <h3 class="prod-i-ttl"><a href="product.html">Universal Plug</a></h3>
                </div>
            </div>
        </article>
    </div>