web/urls.py
from django.urls import path

from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index,name='index'),
    path('productosPorCategoria/<int:categoria_id>',views.productosPorCategoria,name='productosPorCategoria'),
    path('productosPorNombre',views.productosPorNombre,name='productosPorNombre'),
    path('producto/<int:producto_id>',views.productoDetalle,name='producto'),
    path('carrito',views.carrito,name='carrito'),
    path('agregarCarrito/<int:producto_id>',views.agregarCarrito,name='agregarCarrito'),
    path('eliminarProductoCarrito/<int:producto_id>',views.eliminarProductoCarrito,name='eliminarProductoCarrito'),
    path('limpiarCarrito',views.limpiarCarrito,name='limpiarCarrito'),
    path('crearUsuario',views.crearUsuario,name='crearUsuario'),
    path('cuenta',views.cuentaUsuario,name='cuentaUsuario'),
    path('actualizarCliente',views.actualizarCliente,name='actualizarCliente'),
    path('login',views.loginUsuario,name='loginUsuario'),
    path('logout',views.logoutUsuario,name='logoutUsuario'),
    path('registrarPedido',views.registrarPedido,name='registrarPedido'),
    path('confirmarPedido',views.confirmarPedido,name='confirmarPedido'),
    path('gracias',views.gracias,name='gracias')
] 

web/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    categoria = models.ForeignKey(Categoria,on_delete=models.RESTRICT)
    nombre = models.CharField(max_length=200)
    descripcion= models.TextField(null=True)
    precio = models.DecimalField(max_digits=9,decimal_places=2)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    imagen = models.ImageField(upload_to='productos',blank=True)
    
    def __str__(self):
        return self.nombre
    
from django.contrib.auth.models import User

class Cliente(models.Model):
    usuario = models.OneToOneField(User,on_delete=models.RESTRICT)
    dni = models.CharField(max_length=8)
    sexo = models.CharField(max_length=1,default='M')
    telefono = models.CharField(max_length=20)
    fecha_nacimiento = models.DateField(null=True)
    direccion = models.TextField()
    
    def __str__(self):
        return self.dni
    
class Pedido(models.Model):
    
    ESTADO_CHOICES = (
        ('0','Solicitado'),
        ('1','Pagado')
    )
    
    cliente = models.ForeignKey(Cliente,on_delete=models.RESTRICT)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    nro_pedido = models.CharField(max_length=20,null=True)
    monto_total = models.DecimalField(max_digits=10,decimal_places=2,default=0)
    estado = models.CharField(max_length=1,default='0',choices=ESTADO_CHOICES)
    
    def __str__(self):
        return self.nro_pedido
    
class PedidoDetalle(models.Model):
    pedido = models.ForeignKey(Pedido,on_delete=models.RESTRICT)
    producto = models.ForeignKey(Producto,on_delete=models.RESTRICT)
    cantidad = models.IntegerField(default=1)
    subtotal = models.DecimalField(max_digits=10,decimal_places=2)
    
    def __str__(self):
        return self.producto.nombre
    

web/templates/carrito.html
{% extends 'layout.html' %}
{% block content %}
    <h1 class="maincont-ttl">Carrito</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>Carrito</li>
    </ul>
    <div class="page-styling">
    <div class="woocommerce prod-litems section-list">
        {% for key,value in request.session.cart.items %}
            <article class="prod-li sectls">
                <div class="prod-li-inner">
                    <a href="product.html" class="prod-li-img">
                        <img src="{{value.imagen}}" alt="">
                    </a>
                    <div class="prod-li-cont">
                        <div class="prod-li-ttl-wrap">
                            <p>
                                <a href="#">{{value.categoria}}</a>
                            </p>
                            <h3><a href="product.html">{{value.nombre}}</a></h3>
                        </div><!--
                    No Space
                    -->
                        <div class="prod-li-prices">
                            <div class="prod-li-price-wrap">
                                <p>Precio</p>
                                <p class="prod-li-price">${{value.precio}}</p>
                            </div>
                            <div class="prod-li-qnt-wrap">
                                <p class="qnt-wrap prod-li-qnt">
                                    <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                    <input type="text" value="{{value.cantidad}}">
                                    <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                                </p>
                            </div>
                            <div class="prod-li-total-wrap">
                                <p>Total</p>
                                <p class="prod-li-total">${{value.subtotal}}</p>
                            </div>
                        </div><!--
                No Space
                -->
                    </div>
                    <div class="prod-li-info">
                        <div class="prod-li-rating-wrap">
                            <p data-rating="5" class="prod-li-rating">
                                <i class="rating-ico" title="1"></i><i class="rating-ico" title="2"></i><i class="rating-ico"
                                    title="3"></i><i class="rating-ico" title="4"></i><i class="rating-ico" title="5"></i>
                            </p>
                            <p class="prod-li-rating-count">12</p>
                        </div>
                        <p class="prod-li-add">
                            <a href="{% url 'web:eliminarProductoCarrito' value.producto_id %}" class="button hover-label prod-addbtn"><i
                                    class="icon ion-close-round"></i><span>Eliminar</span></a>
                        </p>
                        <p class="prod-li-information">
                            <a href="#" class="hover-label"><i class="icon ion-more"></i><span>Show Information</span></a>
                        </p>
                    </div>
                </div>
            </article>
        {% endfor %}
    </div>


    <div class="cart-actions">
        <div class="coupon">
            <input type="text" placeholder="Coupon code">
            <input type="submit" class="button" value="Apply">
        </div>
        <div class="cart-collaterals">
            <a href="{% url 'web:limpiarCarrito' %}" class="checkout-button button">Limpiar Carrito</a>
            <a href="{% url 'web:registrarPedido' %}" class="checkout-button button">Realizar Pedido</a>
            <div class="order-total">
                <p class="cart-totals-ttl">Total</p>
                <p class="cart-totals-val">${{request.session.cartMontoTotal}}</p>
            </div>
        </div>
    </div>


</div>

{% endblock %}

web/templates/compra.html
{% extends 'layout.html' %}
{% block content %}
<h1 class="maincont-ttl">PEDIDO NRO : {{pedido.nro_pedido}}</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>Pedido</li>
    </ul>
<div class="page-styling">
    <div class="woocommerce prod-litems section-list">
            <h2>Fecha : {{pedido.fecha_registro}}</h2>
            {%for detalle in pedido.pedidodetalle_set.all %}
            <article class="prod-li sectls">
                <div class="prod-li-inner">
                    <a href="#" class="prod-li-img">
                        <img src="{{detalle.producto.imagen.url}}" alt="">
                    </a>
                    <div class="prod-li-cont">
                        <div class="prod-li-ttl-wrap">
                            <p>
                                <a href="#">{{detalle.producto.categoria}}</a>
                            </p>
                            <h3><a href="product.html">{{detalle.producto.nombre}}</a></h3>
                        </div>
                        <div class="prod-li-prices">
                            <div class="prod-li-price-wrap">
                                <p>Precio</p>
                                <p class="prod-li-price">${{detalle.producto.precio}}</p>
                            </div>
                        </div>
                        <div class="prod-li-qnt-wrap">
                            <p class="qnt-wrap prod-li-qnt">
                                <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                <input type="text" value="{{detalle.cantidad}}">
                                <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                            </p>
                        </div>
                        <div class="prod-li-total-wrap">
                            <p>Total</p>
                            <p class="prod-li-total">${{detalle.subtotal}}</p>
                        </div>
                    </div>
                </div>
            </article>
            {% endfor %}
    </div>
    <div class="cart-actions">
            <div class="cart-collaterals">
                {{formPaypal.render}}
                <div class="order-total">
                    <p class="cart-totals-ttl">Total</p>
                    <p class="cart-totals-val">${{pedido.monto_total}}</p>
                </div>
            </div>
    </div>
</div>
{% endblock %}

web/templates/cuenta.html
{% extends 'layout.html' %}
{% block content %}
<h1 class="maincont-ttl">Bienvenido - {{user.username }}</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>Mi Cuenta</li>
    </ul>
    <h2>{{mensaje}}</h2>
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <h2>Datos Personales</h2>
                    <form method="post" action="{% url 'web:actualizarCliente' %}" class="register">
                        {% csrf_token %}
                        {{frmCliente}}
                        <p class="auth-submit">
                            <input type="submit" value="Actualizar Datos">
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </article>
{% endblock %}

web/templates/gracias.html
{% extends 'layout.html' %}
{% block content %}
<h1 class="maincont-ttl">Checkout OK</h1>
    <ul class="b-crumbs">
        <li><a href="index.html">Home</a></li>
        <li>COMPRA</li>
    </ul>
    <h2>GRACIAS POR TU COMPRA</h2>
    <h3>Nro de Pedido : {{pedido.nro_pedido}}</h3>
    <p>Te estaremos enviando un correo confirmando tu pedido</p>    
{% endblock %}

web/templates/index.html
{% extends 'layout.html' %}
{% block content %}
        <div class="section-top">

            <h1 class="maincont-ttl">Catalogo</h1>
            <ul class="b-crumbs">
                <li><a href="/">Inicio</a></li>
                <li>Catalogo</li>
            </ul>
        </div>
        <!-- To make Sidebar "Not Sticky" just remove  id="section-list-withsb" -->
        <div class="section-wrap-withsb">
            <aside class="blog-sb-widgets section-sb" id="section-sb">
                <div class="theiaStickySidebar">
                    <p class="section-filter-toggle filter_hidden">
                        <a href="#" id="section-filter-toggle-btn">Filtros</a>
                    </p>
                    <div class="section-filter">
                        <div class="section-filter">
                            {% include 'includes/catalogo/categorias.html' %}
                        </div>
                    </div>
                </div>
            </aside>        <div class="section-list-withsb" id="section-list-withsb">
            <div class="theiaStickySidebar">
                {% include 'includes/catalogo/catalogo.html' %}
            </div><!-- .theiaStickySidebar -->
        </div><!-- .section-list-withsb -->
        </div><!-- .section-wrap-withsb -->
{% endblock %}

web/templates/layout.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>EdShop</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no">

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,900%7COpen+Sans:300,300i,400,400i,600,600i,700,700i&amp;subset=cyrillic" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.formstyler.css' %}">
    <link rel="stylesheet" href="{% static 'css/flexslider.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.css' %}">
    <link rel="stylesheet" href="{% static 'css/ion.rangeSlider.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.mThumbnailScroller.css' %}">
    <link rel="stylesheet" href="{% static 'css/chosen.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/elements.css' %}">
    <link rel="stylesheet" href="{% static 'css/media.css' %}">
    <link rel="stylesheet" href="{% static 'css/elements-media.css' %}">

</head>
<body>
<div id="page" class="site">

    {% include 'includes/navbar.html' %}

    {% include 'includes/header.html' %}

    <div id="content" class="site-content">
        <div id="primary" class="content-area">
            <main id="main" class="site-main">
                <div class="cont maincont">
                    {% block content %}
                    {% endblock %}
                </div>
            </main><!-- #main -->
        </div><!-- #primary -->

    </div><!-- #content -->

    {% include 'includes/footer.html' %}
</div><!-- #page -->

<script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'js/jquery-plugins.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

web/templates/login.html
{% extends 'layout.html' %}
{% block content %}
    <h1 class="maincont-ttl">Registration / Login</h1>
    <ul class="b-crumbs">
        <li><a href="index.html">Home</a></li>
        <li>Registration & Login</li>
    </ul>                                                <article class="page-cont">
    <div class="page-styling">


        <div class="auth-wrap">
            <div class="auth-col">
                <h2>Login</h2>
                <form method="post" class="login" action="{% url 'web:loginUsuario' %}">
                    {% csrf_token %}
                    <input type="hidden" name="destino" value="{{destino}}"/>
                    <p>
                        <label for="username">E-mail <span class="required">*</span></label>
                        <input type="text" id="username" name="usuario">
                    </p>
                    <p>
                        <label for="password">Password <span class="required">*</span></label>
                        <input type="password" id="password" name="password">
                    </p>
                    <p class="auth-submit">
                        <input type="submit" value="Login">
                        <input type="checkbox" id="rememberme" value="forever">
                        <label for="rememberme">Remember me</label>
                    </p>
                    <p>
                        <label for="alert-danger">{{mensajeError}}</label>
                    </p>
                </form>
            </div>
            <div class="auth-col">
                <h2>Registro</h2>
                <form method="post" class="register" action="{% url 'web:crearUsuario' %}">
                    {% csrf_token %}
                    <p>
                        <label for="reg_email">Email <span class="required">*</span></label>
                        <input type="email" id="reg_email" name="nuevoUsuario">
                    </p>
                    <p>
                        <label for="reg_password">Password <span class="required">*</span></label>
                        <input type="password" id="reg_password" name="nuevoPassword">
                    </p>
                    <p class="auth-submit">
                        <input type="submit" value="Crear Cuenta">
                    </p>
                </form>
            </div>
        </div>


    </div>
</article>

{% endblock %}

web/templates/payment.html
<h1>Show me the money!</h1>
<!-- writes out the form tag automatically -->
{{ form.render }}

web/templates/pedido.html
{% extends 'layout.html' %}
{% block content %}
<h1 class="maincont-ttl">REGISTRO DE PEDIDO</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>pedido</li>
    </ul>
    <form method="post" action="{% url 'web:confirmarPedido' %}" class="register">
    {% csrf_token %}
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <h2>Datos Personales</h2>
                    <p>
                        <label for="username">Nombres<span class="required">*</span></label>
                        {{frmCliente.nombre}}
                    </p>
                    <p>
                        <label for="username">Apellidos<span class="required">*</span></label>
                        {{frmCliente.apellidos}}
                    </p>
                </div>
                <div class="auth-col">
                    <h2>Datos Envio</h2>
                    <p>
                        <label for="username">Telefono<span class="required">*</span></label>
                        {{frmCliente.telefono}}
                    </p>
                    <p>
                        <label for="username">Dirección<span class="required">*</span></label>
                        {{frmCliente.direccion}}
                    </p>
                </div>
            </div>
        </div>
    </article>
    <article class="page-cont">
        <div class="page-styling">
            <h2>Confirmación de Productos</h2>
            <div class="woocommerce prod-litems section-list">
                {% for key,value in request.session.cart.items %}
                <article class="prod-li sectls">
                    <div class="prod-li-inner">
                        <a href="#" class="prod-li-img">
                            <img src="{{ value.imagen }}" alt="">
                        </a>
                        <div class="prod-li-cont">
                            <div class="prod-li-ttl-wrap">
                                <p>
                                    <a href="#">value.categoria</a>
                                </p>
                                <h3><a href="product.html">{{ value.nombre }}</a></h3>
                            </div>
                            <div class="prod-li-prices">
                                <div class="prod-li-price-wrap">
                                    <p>Precio</p>
                                    <p class="prod-li-price">${{value.precio}}</p>
                                </div>
                            </div>
                            <div class="prod-li-qnt-wrap">
                                <p class="qnt-wrap prod-li-qnt">
                                    <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                    <input type="text" value="{{value.cantidad}}">
                                    <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                                </p>
                            </div>
                            <div class="prod-li-total-wrap">
                                <p>Total</p>
                                <p class="prod-li-total">${{value.subtotal}}</p>
                            </div>
                        </div>
                    </div>
                </article>
                {% endfor %}
        </div>
        <div class="cart-actions">
                <div class="cart-collaterals">
                    <div class="order-total">
                        <p class="cart-totals-ttl">Total</p>
                        <p class="cart-totals-val">${{request.session.cartMontoTotal}}</p>
                    </div>
                </div>
        </div>
        </div>
    </article>
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <p class="auth-submit">
                        <input type="submit" value="Confirmar Pedido">
                    </p>
            </div>
        </div>
    </article>
    </form>
{% endblock %}

web/templates/plantilla.html
{% extends 'layout.html' %}
{% block content %}
{% endblock %}

web/templates/producto.html
{% extends 'layout.html' %}
{% block content %}
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li><a href="/">Catalog</a></li>
        <li>Producto</li>
    </ul>
    <article>
    <div class="prod">
        <div class="prod-slider-wrap prod-slider-shown">
            <div class="flexslider prod-slider" id="prod-slider">
                <ul class="slides">
                    <li>
                        <a data-fancybox-group="prod" class="fancy-img" href="#">
                            {% if producto.imagen %}
                                <img src="{{producto.imagen.url}}" alt="">
                            {% else %}
                                <img src="https://via.placeholder.com/250" alt="">
                            {% endif %}
                            
                        </a>
                    </li>
                    <li>
                        <a data-fancybox-group="prod" class="fancy-img" href="#">
                            {% if producto.imagen %}
                                <img src="{{producto.imagen.url}}" alt="">
                            {% else %}
                                <img src="https://via.placeholder.com/250" alt="">
                            {% endif %}
                        </a>
                    </li>
                </ul>
                <div class="prod-slider-count"><p>
                    <span class="count-cur">1</span> / <span class="count-all">2</span></p><p class="hover-label prod-slider-zoom">
                    <i class="icon ion-search"></i><span>Zoom In</span></p></div>
            </div>
            <div class="flexslider prod-thumbs" id="prod-thumbs">
                <ul class="slides">
                    <li>
                        {% if producto.imagen %}
                                <img src="{{producto.imagen.url}}" alt="">
                            {% else %}
                                <img src="https://via.placeholder.com/250" alt="">
                            {% endif %}
                    </li>
                    <li>
                        {% if producto.imagen %}
                                <img src="{{producto.imagen.url}}" alt="">
                            {% else %}
                                <img src="https://via.placeholder.com/250" alt="">
                            {% endif %}
                    </li>
                </ul>
            </div>
        </div>

        <div class="prod-cont">
            <div class="prod-rating-wrap">
                <p data-rating="4" class="prod-rating">
                    <i class="rating-ico" title="1"></i>
                    <i class="rating-ico" title="2"></i>
                    <i class="rating-ico" title="3"></i>
                    <i class="rating-ico" title="4"></i>
                    <i class="rating-ico" title="5"></i>
                </p>
                <p class="prod-rating-count">7</p>
            </div>
            <p class="prod-categs"><a href="#">{{producto.categoria}}</a></p>
            <h1>{{producto.nombre}}</h1>
            <div class="variations_form cart">
                <p class="prod-price">${{producto.precio}}</p>
                <p class="prod-excerpt">{{producto.descripcion}}... 
                    <a id="prod-showdesc" class="prod-excerpt-more" href="#">read more</a></p>
                <div class="prod-add">
                    <form action="{% url 'web:agregarCarrito' producto.id %}" method="post">
                        {% csrf_token %}
                        <div class="variations">
                            <div class="variations-row">
                                <div class="label"><label >Сolor</label></div>
                                <div class="value">
                                    <select>
                                        <option value="">Choose an option</option>
                                        <option value="blue">Blue</option>
                                        <option value="green">Green</option>
                                        <option value="yellow">Yellow</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="button"><i class="icon ion-android-cart"></i> Agregar al Carrito</button>
                        <p class="qnt-wrap prod-li-qnt">
                            <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                            <input type="text" name="cantidad" value="1">
                            <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                        </p>
                    </form>
                </div>
            </div>
            <div class="prod-props">
                <dl class="product_meta">
                    
                    
                </dl>
            </div>
        </div>
    </div>


    

</article>

{% endblock %}