web/urls.py
from django.urls import path

from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index,name='index'),
    path('productosPorCategoria/<int:categoria_id>',views.productosPorCategoria,name='productosPorCategoria'),
    path('productosPorNombre',views.productosPorNombre,name='productosPorNombre'),
    path('producto/<int:producto_id>',views.productoDetalle,name='producto'),
    path('carrito',views.carrito,name='carrito'),
    path('agregarCarrito/<int:producto_id>',views.agregarCarrito,name='agregarCarrito'),
    path('eliminarProductoCarrito/<int:producto_id>',views.eliminarProductoCarrito,name='eliminarProductoCarrito'),
    path('limpiarCarrito',views.limpiarCarrito,name='limpiarCarrito'),
    path('crearUsuario',views.crearUsuario,name='crearUsuario'),
    path('cuenta',views.cuentaUsuario,name='cuentaUsuario'),
    path('actualizarCliente',views.actualizarCliente,name='actualizarCliente'),
    path('login',views.loginUsuario,name='loginUsuario'),
    path('logout',views.logoutUsuario,name='logoutUsuario'),
    path('registrarPedido',views.registrarPedido,name='registrarPedido'),
    path('confirmarPedido',views.confirmarPedido,name='confirmarPedido'),
    path('gracias',views.gracias,name='gracias')
] 

web/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    categoria = models.ForeignKey(Categoria,on_delete=models.RESTRICT)
    nombre = models.CharField(max_length=200)
    descripcion= models.TextField(null=True)
    precio = models.DecimalField(max_digits=9,decimal_places=2)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    imagen = models.ImageField(upload_to='productos',blank=True)
    
    def __str__(self):
        return self.nombre
    
from django.contrib.auth.models import User

class Cliente(models.Model):
    usuario = models.OneToOneField(User,on_delete=models.RESTRICT)
    dni = models.CharField(max_length=8)
    sexo = models.CharField(max_length=1,default='M')
    telefono = models.CharField(max_length=20)
    fecha_nacimiento = models.DateField(null=True)
    direccion = models.TextField()
    
    def __str__(self):
        return self.dni
    
class Pedido(models.Model):
    
    ESTADO_CHOICES = (
        ('0','Solicitado'),
        ('1','Pagado')
    )
    
    cliente = models.ForeignKey(Cliente,on_delete=models.RESTRICT)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    nro_pedido = models.CharField(max_length=20,null=True)
    monto_total = models.DecimalField(max_digits=10,decimal_places=2,default=0)
    estado = models.CharField(max_length=1,default='0',choices=ESTADO_CHOICES)
    
    def __str__(self):
        return self.nro_pedido
    
class PedidoDetalle(models.Model):
    pedido = models.ForeignKey(Pedido,on_delete=models.RESTRICT)
    producto = models.ForeignKey(Producto,on_delete=models.RESTRICT)
    cantidad = models.IntegerField(default=1)
    subtotal = models.DecimalField(max_digits=10,decimal_places=2)
    
    def __str__(self):
        return self.producto.nombre
    

web/templates/includes/catalogo/catalogo.html
<div class="row prod-items prod-items-2">
    {% for producto in productos %}
    <article class="cf-sm-6 cf-md-6 cf-lg-6 col-xs-6 col-sm-6 col-md-6 col-lg-6 sectgl-item">
        <div class="sectgl prod-i">
            <div class="prod-i-top">
                <a class="prod-i-img" href="{% url 'web:producto' producto.id %}">
                    {% if producto.imagen %}
                        <img src="{{producto.imagen.url}}" alt="">
                    {% else %}
                        <img src="https://via.placeholder.com/250" alt="">
                    {% endif %}
                </a>
                <div class="prod-i-actions">
                    <div class="prod-i-actions-in">
                        <p class="prod-i-cart">
                            <a href="{% url 'web:agregarCarrito' producto.id %}" class="hover-label prod-addbtn"><i class="icon ion-android-cart"></i><span>Añadir al carrito</span></a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="prod-i-bot">
                <div class="prod-i-info">
                    <p class="prod-i-price">${{producto.precio}}</p>
                    <p class="prod-i-categ"><a href="#">{{producto.categoria}}</a></p>
                </div>
                <h3 class="prod-i-ttl"><a href="{% url 'web:producto' producto.id %}">{{producto.nombre}}</a></h3>
            </div>
        </div>
    </article>
    {% endfor %}
</div>

web/templates/includes/catalogo/categorias.html
<div class="blog-sb-widget multishopcategories_widget">
    <h3 class="widgettitle">Categorias</h3>
    <div class="section-sb-current">
        <ul class="section-sb-list">
            {% for categoria in categorias %}
            <li>
                <a href="{% url 'web:productosPorCategoria' categoria.id %}">
                    <span class="section-sb-label">{{categoria.nombre}} 
                        <span class="count">{{categoria.producto_set.all.count}}</span>
                    </span>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>